apiVersion: v1
kind: Secret
metadata:
  name: minio-user
  heritage: deis
type: Opaque
data:
  access-cert: OFRaUlkySlJXTVBUNlVNWFI2STUK
  access-pem: Z2JzdHJPdm90TU1jZzJzTWZHVWhBNWE2RXQvRUk1QUx0SUhzb2JZawo=
