apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-minio
  labels:
    heritage: deis
    release: 0.0.1-20151125145149
spec:
  replicas: 1
  selector:
    app: deis-minio
  template:
    metadata:
      labels:
        app: deis-minio
    spec:
      containers:
        - imagePullPolicy: Always
          name: deis-minio
          ports:
            - containerPort: 9000
          command:
            - boot
          args:
            - "server"
            - "--cert=/var/run/secrets/deis/minio/ssl/access-cert"
            - "--key=/var/run/secrets/deis/minio/ssl/access-pem"
            - "/home/minio/"
          volumeMounts:
            - name: minio-admin
              mountPath: /var/run/secrets/deis/minio/admin
              readOnly: true
            - name: minio-user
              mountPath: /var/run/secrets/deis/minio/user
              readOnly: true
            - name: minio-ssl
              mountPath: /var/run/secrets/deis/minio/ssl
              readOnly: true
      volumes:
        - name: minio-admin
          secret:
            secretName: minio-admin
        - name: minio-user
          secret:
            secretName: minio-user
        - name: minio-ssl
          secret:
            secretName: minio-ssl
